---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-app
  namespace: default
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: "python:3.8-slim-buster"
        ports:
          - containerPort: 5000
