apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  selector:
    matchLabels:
      app: python
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python3
        image: python:3.8-slim-buster
        ports:
        - containerPort: 5000
